general : updates

diff --git a/sdcard b/sdcard
--- a/sdcard
+++ b/sdcard
@@ -5,13 +5,15 @@
 mnt=/mnt/sdcard
 dev=/dev/mmcblk0p1
 
-check ()
+_ ()
 {
-    [ -e "$1" ] ||
-        { echo "error : '$1' not found"; exit 1; }
+    if [ -e "$1" ]; then
+        echo "error : '$1' not found"
+        exit 1
+    fi
 }
 
-check "$mnt"
-check "$dev"
+_ "$mnt"
+_ "$dev"
 
 sudo mount "$dev" "$mnt"
