update chdler

diff --git a/scripts/.local/bin/chdler b/scripts/.local/bin/chdler
--- a/scripts/.local/bin/chdler
+++ b/scripts/.local/bin/chdler
@@ -7,14 +7,16 @@
     exit 1
 }
 
-declare -A array
-
 while read -rd \< line; do
-    [[ $line =~ ('//is2.4chan.org/'[^\"]+) ]] &&
-        array[https:${BASH_REMATCH[1]}]=1
+    [[ $line =~ 'a href="'('//is2.4chan.org/'[^\"]+) ]] &&
+        array+=("https:${BASH_REMATCH[1]}")
 done < <(curl -s "$1")
 
-for file in "${!array[@]}"; {
-    wget "$file" &> /dev/null &&
-        echo "'${file##*/}' downloaded"
+for file in "${array[@]}"; {
+    wget "$file" &> /dev/null || {
+        echo "error : downloading '${file##*/}' failed" >&2
+        exit 1
+    }
+
+    echo "downloaded '${file##*/}'"
 }
