better handling of errors in extract script

diff --git a/scripts/.local/bin/extract b/scripts/.local/bin/extract
--- a/scripts/.local/bin/extract
+++ b/scripts/.local/bin/extract
@@ -3,20 +3,20 @@
 # extract - extract common archive formats
 
 die() {
-    echo "usage : ${0##*/} [file...]" >&2
+    echo "$1" >&2
     exit 1
 }
 
-test "$1" || die
+test "$1" || die "usage : ${0##*/} [file...]"
 
 for file; do
-    test -f "$file" || die
+    test -f "$file" || die "usage : ${0##*/} [file...]"
 
     case $file in
         *.tar.bz2|*.tar.gz|*.tar.xz|*.tar|*.tgz|*.xz) tar xvf "$file";;
         *.zip)   unzip "$file";;
         *.gz)   gunzip "$file";;
         *.rar) unrar e "$file";;
-        *) echo "'$1' cannot be extracted via ${0##*/}" >&2
+        *) die "error : '$1' cannot be extracted via ${0##*/}"
     esac
 done
